import React from 'react';
import styles from './intro.module.css';

export const Intro: React.FC<{onClose: (canStore: boolean)=> void}> = ({ onClose }) => {

    const handleClose = (canStore: boolean) => () => onClose(canStore === true);

    return (
        <div className={styles.container}>
            <div className={styles.root}>
                <h2>Hello there,</h2>

                <p>This is an experiment of identifying a browser on a machine without using 3rd party cookies.</p>
                <p>The identification is done by collecting attributes from Browser APIs and then combining such information to a single hash.</p>
                <p>Attributes that this experiment collects:</p>
                <ul>
                    <li>Screen size (width, and height)</li>
                    <li>User preferred languages</li>
                    <li>Information about graphical renderer (WebGL)</li>
                    <li>Data URI representation of an image generated by your hardware via Canvas API.</li>
                </ul>
                
                <p>You can opt-in to save the actual records to your device via LocalStorage API. This way you will be able to inspect your identifiers over the time.</p>
                <p>Please choose which mode you would like to continue.</p>

                <div className={styles.buttonGroup}>
                    <button onClick={handleClose(true)} className={styles.button}>Enable Storage</button>
                    <button onClick={handleClose(false)} className={styles.button}>Disable Storage</button>
                </div>

                <p>You can opt-out by clearing the history.</p>
            </div>
        </div>
    );
}